//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvetlinAnkov.AlbiteREADER.Resources.Defaults {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineDefaults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineDefaults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvetlinAnkov.AlbiteREADER.Resources.Defaults.EngineDefaults", typeof(EngineDefaults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.css.
        /// </summary>
        internal static string BaseStyles {
            get {
                return ResourceManager.GetString("BaseStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book/.
        /// </summary>
        internal static string BookPath {
            get {
                return ResourceManager.GetString("BookPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.css.
        /// </summary>
        internal static string ContentStyles {
            get {
                return ResourceManager.GetString("ContentStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albite.js.
        /// </summary>
        internal static string JSEngine {
            get {
                return ResourceManager.GetString("JSEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout/.
        /// </summary>
        internal static string LayoutPath {
            get {
                return ResourceManager.GetString("LayoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.xhtml.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.css.
        /// </summary>
        internal static string ThemeStyles {
            get {
                return ResourceManager.GetString("ThemeStyles", resourceCulture);
            }
        }
    }
}
