//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvetlinAnkov.Albite.READER.Resources.Defaults {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutDefaults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutDefaults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvetlinAnkov.Albite.READER.Resources.Defaults.LayoutDefaults", typeof(LayoutDefaults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #634F3B.
        /// </summary>
        internal static string DayThemeAccentColor {
            get {
                return ResourceManager.GetString("DayThemeAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        internal static string DayThemeBackroundColor {
            get {
                return ResourceManager.GetString("DayThemeBackroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        internal static string DayThemeTextColor {
            get {
                return ResourceManager.GetString("DayThemeTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Justified {
            get {
                return ResourceManager.GetString("Justified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140.
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0375.
        /// </summary>
        internal static string MarginBottom {
            get {
                return ResourceManager.GetString("MarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0375.
        /// </summary>
        internal static string MarginLeft {
            get {
                return ResourceManager.GetString("MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0375.
        /// </summary>
        internal static string MarginRight {
            get {
                return ResourceManager.GetString("MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0375.
        /// </summary>
        internal static string MarginTop {
            get {
                return ResourceManager.GetString("MarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #634F3B.
        /// </summary>
        internal static string NightThemeAccentColor {
            get {
                return ResourceManager.GetString("NightThemeAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        internal static string NightThemeBackgroundColor {
            get {
                return ResourceManager.GetString("NightThemeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        internal static string NightThemeTextColor {
            get {
                return ResourceManager.GetString("NightThemeTextColor", resourceCulture);
            }
        }
    }
}
